version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: documind-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app:/app/contexts
      - DATABASE_URL=sqlite:///./data/qms.db
    volumes:
      - ./backend:/app/backend
      - ./contexts:/app/contexts
      - ./data:/app/data  # Shared database directory (Host mount)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: documind-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: documind-network
